server:
  port: 4555

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: PCQ Consolidation Service

ccd.data.store.api:
  host: http://localhost:4452
  caseMatchingPath: /searchCases

idam:
  s2s-auth:
    url:    ${S2S_URL:http://localhost:4552}
    secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
    name:   ${S2S_NAME:pcq_consolidation_service}
  api:
    url: http://localhost:8080
  client:
    id: 'pcq'
    secret: ${IDAM_CLIENT_SECRET:123456}
    redirect_uri: http://localhost/receiver
  users:
    pcq:
      username: ${IDAM_USER_PCQ_USERNAME:pcquser+ccd@gmail.com}
      password: ${IDAM_USER_PCQ_PASSWORD:Pa55word11}

services-config:
  - service: pcqtest
    jurisdiction: PCQTEST
    case-type-ids:
      - Questions2

smoke.test.enabled: false

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:"Test"}

pcqBackendUrl: ${PCQ_BACKEND_URL:http://localhost:4550}

feign:
  allow:
    headers:
      - x-correlation-id

coRelationId: PCQ Consolidation Service

