server:
  port: 4555

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: PCQ Consolidation Service

core_case_data:
  api:
    url: 'http://localhost:4452'

idam:
  s2s-auth:
    #url:    ${S2S_URL:http://localhost:4552}
    url:    ${S2S_URL:http://localhost:4502}
    secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
    name:   ${S2S_NAME:pcq_consolidation_service}
  api:
    #url: http://localhost:8080
    url: http://localhost:5000
  client:
    #id: 'pcq'
    #secret: ${IDAM_CLIENT_SECRET:123456}
    #redirect_uri: http://localhost/receiver
    id: 'ccd_gateway'
    secret: ${IDAM_CLIENT_SECRET:ccd_gateway_secret}
    redirect_uri: http://localhost:3451/oauth2redirect
  users:
    pcq:
      username: ${IDAM_USER_PCQ_USERNAME:pcq-extractor+ccd@gmail.com}
      password: ${IDAM_USER_PCQ_PASSWORD:Pa55word11}

service-config:
  services:
    - service: pcqtest
      jurisdiction: PCQTEST
      case-type-ids:
        - Questions2

smoke.test.enabled: false

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:"Test"}

pcqBackendUrl: ${PCQ_BACKEND_URL:http://localhost:4550}

feign:
  allow:
    headers:
      - x-correlation-id

coRelationId: PCQ Consolidation Service

