server:
  port: 4555

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  application:
    name: PCQ Consolidation Service

ccd.data.store.api:
  host: http://localhost:4452
  caseMatchingPath: /searchCases

smoke.test.enabled: false

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:""}

pcqBackendUrl: ${PCQ_BACKEND_URL:http://localhost:4550}

feign:
  allow:
    headers:
      - X-Correlation-Id

coRelationId: PCQ Consolidation Service